### ISSUE TITLE
Difference between Brain_19 & Brain_19_5

### ISSUE THREAD

**Issue by Shantan243** [Cernewein/multi-building-RL#2]
Hi Cernewein,
Greetings!
               Could you please share details what these 19 and 19_5 refers to. I undersatnd that these are Agents but want to know why 19 and 19_5 only?

              Appreciate your support.

Thanks..

**Comment by Cernewein** [comment]
Hi,

Those two agents were trained using two different minimum temperature settings (19°C and 19.5°C). This was done in order to generate two different behaviors. You can choose whatever setting you want during training, but in my opinion the multi-agent problem is more interesting when considering different agent behaviors

Best,

**Comment by Shantan243** [comment]
Thanks Cernewein.
