### ISSUE TITLE
n_actions=12

### ISSUE THREAD

**Issue by Shantan243** [Cernewein/multi-building-RL#3]
Can i have detailed explaination of why 12 actions only - i mean, we can set price list as we wish. And also, how these 12 actions are impacting multiple buildings, say 10  buildings in this repo. Will 12 actions hit each of the buildings simultaneously or 1 action per building or a combination of actions per building..

**Comment by Cernewein** [comment]
Hi,

This was done in order to discretize the action space, which simplifies training a lot. At one timestep on action is chosen (one price), and this same price is sent to all individual buildings.
You can increase the number of actions but it makes it harder to explore all of the action space, 12 seemed like a reasonable trade off between action granularity and training complexity.
